"""Smoke-test a solution notebook as a Databricks one-off job.

Same upload / submit / poll / fetch-output pattern as
scripts/run_smoke_job.py, but accepts ANY solution notebook and injects a
synthetic STUDENT_ID at the top so the notebook runs as the smoke identity
(default 60) instead of falling through to the cluster user's identity.

Usage:
    python3 scripts/smoke/run_week_smoke.py \
        --notebook solutions/week_22_airflow_production_loop/week_22_airflow_production_loop.ipynb \
        --cluster-id 0512-181411-pzxqam5e \
        --student-id 60

Exit code 0 on SUCCESS, 1 on FAILED.
"""

import argparse
import base64
import configparser
import json
import os
import sys
import time

import requests


def databricks_config():
    cfg = configparser.ConfigParser()
    cfg.read(os.path.expanduser("~/.databrickscfg"))
    d = cfg["DEFAULT"]
    return d["host"].rstrip("/"), d["token"]


def make_override(student_id: int) -> str:
    """Prelude that sets BREAD_SMOKE_STUDENT_ID and monkey-patches the %pip
    magic so pip's stdout/stderr land in the captured notebook output.

    Databricks' built-in PipMagicHandler swallows pip output and only
    re-raises CalledProcessError on failure, which makes it impossible to
    debug a pip install failure from the job-runs/get-output payload.
    The shim below replaces the line_magic so the subprocess output is
    routed through print() (which DOES land in notebook_output) before
    the failure propagates.
    """
    return f"""# SMOKE override: pretend to be student-{student_id:02d} AND make %pip verbose.
# The notebook's setup cell reads BREAD_SMOKE_STUDENT_ID before deriving
# the student number from the Databricks user, so the env var redirects
# the entire notebook (secret scope, dag_id naming, S3 prefix) to
# student_{student_id:02d}.
import os
import sys
import subprocess

os.environ["BREAD_SMOKE_STUDENT_ID"] = "{student_id:02d}"
print("[smoke] BREAD_SMOKE_STUDENT_ID =", os.environ["BREAD_SMOKE_STUDENT_ID"])

# Replace the IPython %pip magic with a verbose subprocess call so pip's
# stdout/stderr are visible in the job-runs/get-output payload. Without
# this, %pip failures surface as opaque CalledProcessError with no detail.
import shlex
from IPython.core.magic import register_line_magic

@register_line_magic("pip")
def _verbose_pip(line):
    # shlex.split respects shell quoting so "numpy<2" parses as numpy<2
    # not as the literal token '"numpy<2"' which pip rejects.
    cmd = [sys.executable, "-m", "pip"] + shlex.split(line)
    print(f"[smoke] running: {{' '.join(cmd)}}")
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.stdout:
        print("[smoke] pip stdout:")
        print(proc.stdout)
    if proc.stderr:
        print("[smoke] pip stderr:")
        print(proc.stderr)
    if proc.returncode != 0:
        # dbutils.notebook.exit lands the message in notebook_output even
        # though the run reports SUCCESS - we differentiate by message prefix.
        dbutils.notebook.exit(
            f"[smoke] PIP FAILED rc={{proc.returncode}}: "
            f"{{proc.stderr[-1500:] if proc.stderr else proc.stdout[-1500:]}}"
        )
    print(f"[smoke] pip rc=0")
print("[smoke] %pip is now verbose")
"""


def notebook_to_databricks_source(nb_path: str, student_id: int) -> str:
    """Convert .ipynb -> Databricks SOURCE/PYTHON with the override injected
    before any code cell runs."""
    nb = json.load(open(nb_path))

    parts = [
        "# Databricks notebook source",
        "# AUTO-GENERATED by scripts/smoke/run_week_smoke.py - do not hand-edit.",
        "",
        "# COMMAND ----------",
        "",
        make_override(student_id),
    ]

    for c in nb["cells"]:
        if c["cell_type"] != "code":
            continue
        src = c["source"] if isinstance(c["source"], str) else "".join(c["source"])
        parts.append("# COMMAND ----------")
        parts.append("")
        parts.append(src.rstrip("\n"))
        parts.append("")

    parts.append("# COMMAND ----------")
    parts.append("")
    parts.append('dbutils.notebook.exit("smoke OK")')
    parts.append("")

    return "\n".join(parts)


def submit_and_wait(host, token, workspace_path, cluster_id, run_name,
                    poll_seconds=30):
    h = {"Authorization": f"Bearer {token}"}

    r = requests.post(
        f"{host}/api/2.1/jobs/runs/submit",
        headers=h,
        json={
            "run_name": run_name,
            "tasks": [
                {
                    "task_key": "smoke",
                    "existing_cluster_id": cluster_id,
                    "notebook_task": {"notebook_path": workspace_path},
                }
            ],
        },
        timeout=60,
    )
    r.raise_for_status()
    run_id = r.json()["run_id"]
    run_url = f"{host}/#job/run/{run_id}"
    print(f"[runner] submitted run {run_id} ({run_name})")
    print(f"[runner] run URL: {run_url}")

    while True:
        time.sleep(poll_seconds)
        r = requests.get(
            f"{host}/api/2.1/jobs/runs/get",
            headers=h, params={"run_id": run_id}, timeout=60,
        )
        r.raise_for_status()
        state = r.json()["state"]
        life = state["life_cycle_state"]
        print(f"[runner] run {run_id}: {life}")
        if life in ("TERMINATED", "SKIPPED", "INTERNAL_ERROR"):
            result = state.get("result_state")
            msg = state.get("state_message", "")
            print(f"[runner] result: {result} {msg}")
            break

    detail = requests.get(
        f"{host}/api/2.1/jobs/runs/get",
        headers=h, params={"run_id": run_id}, timeout=60,
    ).json()
    task_run_ids = [t["run_id"] for t in detail.get("tasks", [])] or [run_id]
    for trid in task_run_ids:
        r = requests.get(
            f"{host}/api/2.1/jobs/runs/get-output",
            headers=h, params={"run_id": trid}, timeout=60,
        )
        if r.status_code != 200:
            continue
        out = r.json()
        if out.get("error"):
            print("[runner] ERROR:")
            print(out["error"])
        if out.get("error_trace"):
            print("[runner] TRACE:")
            print(out["error_trace"])
        nb_out = out.get("notebook_output", {}).get("result")
        if nb_out:
            print(f"[runner] task {trid} output: {nb_out}")
    print(f"[runner] full logs: {run_url}")
    return result == "SUCCESS"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--notebook", required=True,
                        help="path to solution notebook (relative to repo root)")
    parser.add_argument("--cluster-id", required=True)
    parser.add_argument("--student-id", type=int, default=60)
    parser.add_argument("--poll-seconds", type=int, default=30)
    parser.add_argument("--workspace-prefix", default="/Shared/bread_academy/smoke")
    args = parser.parse_args()

    repo_root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
    nb_path = os.path.join(repo_root, args.notebook)
    if not os.path.exists(nb_path):
        print(f"[runner] notebook not found: {nb_path}")
        sys.exit(2)

    nb_name = os.path.splitext(os.path.basename(nb_path))[0]
    workspace_path = f"{args.workspace_prefix}/{nb_name}_student{args.student_id:02d}"

    source = notebook_to_databricks_source(nb_path, args.student_id)
    print(f"[runner] generated {len(source)} chars of Databricks source")

    host, token = databricks_config()
    h = {"Authorization": f"Bearer {token}"}
    print(f"[runner] Databricks host: {host}")
    print(f"[runner] workspace path:  {workspace_path}")

    # Ensure parent folder exists (workspace/import does not auto-create).
    parent = workspace_path.rsplit("/", 1)[0]
    requests.post(
        f"{host}/api/2.0/workspace/mkdirs",
        headers=h, json={"path": parent}, timeout=30,
    )  # idempotent; 200 whether created or already existed

    r = requests.post(
        f"{host}/api/2.0/workspace/import",
        headers=h,
        json={
            "path": workspace_path,
            "format": "SOURCE",
            "language": "PYTHON",
            "content": base64.b64encode(source.encode()).decode(),
            "overwrite": True,
        },
        timeout=60,
    )
    r.raise_for_status()
    print(f"[runner] uploaded source -> {workspace_path}")

    ok = submit_and_wait(
        host, token, workspace_path, args.cluster_id,
        run_name=f"smoke-{nb_name}-student{args.student_id:02d}",
        poll_seconds=args.poll_seconds,
    )
    sys.exit(0 if ok else 1)


if __name__ == "__main__":
    main()
